name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Step 3: Restore dependencies for TestLib
    - name: Restore dependencies (Library)
      run: dotnet restore TestLib/TestLib.csproj

    # Step 4: Restore dependencies for TestLib.Tests
    - name: Restore dependencies (Tests)
      run: dotnet restore TestLib.Tests/TestLib.Tests.csproj

    # Step 5: Build TestLib
    - name: Build TestLib
      run: dotnet build TestLib/TestLib.csproj --no-restore

    # Step 6: Build TestLib.Tests
    - name: Build TestLib.Tests
      run: dotnet build TestLib.Tests/TestLib.Tests.csproj --no-restore

    # Step 7: Run Tests
    - name: Run tests
      run: dotnet test TestLib.Tests/TestLib.Tests.csproj --no-build --verbosity normal
